Travis fix

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -96,15 +96,14 @@ script:
 #- make distdir PACKAGE=stone VERSION=$HOST
 - mkdir stone-$HOST
 - mkdir stone-$HOST/lib
-#- make depend
+#make depend
 - ls
 - pwd
-- sudo make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && sudo
-  make $GOAL V=1 )
-- if [[ -n "/bin/stone-qt.exe" ]]; then cp /bin/stone* /home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST; 
+- sudo make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && sudo make $GOAL V=1 )
+- if [ -e "/bin/stone-qt.exe" ]; then cp /bin/stone* /home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST; 
   cp /bin/libbitcoinconsensus-0.dll /home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST/; 
-  tar -czvf stone-$HOST.tar.gz stone-$HOST
-  if [[ -e "/home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST.tar.gz" ]]; then 
+  tar -czvf stone-$HOST.tar.gz stone-$HOST 
+  if [ -e "/home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST.tar.gz" ]; then 
   cp /home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST.tar.gz /home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST-$GITCOM.tar.gz
   /home/travis/build/CryptoDragonLady/Stonecoin/scripts/relpush.sh /home/travis/build/CryptoDragonLady/Stonecoin/build/stone-$HOST-$GITCOM.tar.gz
   fi
