travis updates

diff --git a/.travis.yml b/.travis.yml
--- a/.travis.yml
+++ b/.travis.yml
@@ -1,95 +1,161 @@
 sudo: required
 dist: trusty
-group: deprecated-2017Q4
 os: linux
 language: generic
-
 cache:
   apt: true
   ccache: true
   directories:
-    - depends/built
-    - depends/sdk-sources
-    - "$HOME/.ccache"
-
+  - depends/built
+  - depends/sdk-sources
+  - "$HOME/.ccache"
+git:
+  depth: false
+addons:
+  sshknownhosts: 88.198.86.0
 env:
   global:
-    - MAKEJOBS=-j5
-    - RUN_TESTS=false
-    - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
-    - CCACHE_SIZE=400M
-    - CCACHE_TEMPDIR=/tmp/.ccache-temp
-    - CCACHE_COMPRESS=1
-    - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
-    - SDK_URL=https://bitcoincore.org/depends-sources/sdks
-    - PYTHON_DEBUG=1
-    - WINEDEBUG=fixme-all
-
+  - MAKEJOBS=-j4
+  - RUN_TESTS=false
+  - BVER=2.1.0
+  - CHECK_DOC=0
+  - BOOST_TEST_RANDOM=1$TRAVIS_BUILD_ID
+  - CCACHE_SIZE=100M
+  - CCACHE_TEMPDIR=/tmp/.ccache-temp
+  - CCACHE_COMPRESS=1
+  - BASE_OUTDIR=$TRAVIS_BUILD_DIR/out
+  - SDK_URL=https://bitcoincore.org/depends-sources/sdks
+  - PYTHON_DEBUG=1
+  - WINEDEBUG=fixme-all
+  - REMOTEAPPDIR=/var/www/files.worxcoin.io/htdocs/stone/releases/
+  - REMOTEUSER=stone
+  - REMOTEHOST=88.198.86.0
+  - PORT=8080
+  - PPA="ppa:bitcoin/bitcoin"
+  - RBITS=$(cat /dev/urandom | head -c 64 | base64 | tr -cd '[:alnum:]' | head -c
+    8 ;)
   matrix:
+
 # ARM
-    - HOST=arm-linux-gnueabihf PLATFORM="arm-linux" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
+#    - HOST=arm-linux-gnueabihf PLATFORM="arm-linux" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-arm-linux-gnueabihf" DEP_OPTS="NO_QT=1" CHECK_DOC=1 GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
 # Win32
-    - HOST=i686-w64-mingw32 PLATFORM="win32" DPKG_ADD_ARCH="i386" DEP_OPTS="" PPA="ppa:bitcoin/bitcoin" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.7 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" MAKEJOBS="-j4" WINE=true
+#    - HOST=i686-w64-mingw32 PLATFORM="win32" DPKG_ADD_ARCH="i386" DEP_OPTS="" PPA="ppa:bitcoin/bitcoin" PACKAGES="python3 nsis g++-mingw-w64-i686 wine1.7 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" MAKEJOBS="-j4" WINE=true
 # Win64
     - HOST=x86_64-w64-mingw32 PLATFORM="win64" DPKG_ADD_ARCH="i386" DEP_OPTS="" PPA="ppa:bitcoin/bitcoin" PACKAGES="python3 nsis g++-mingw-w64-x86-64 wine1.7 bc" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" MAKEJOBS="-j4" WINE=true
 # Linux 32-bit + stone
-    - HOST=i686-pc-linux-gnu PLATFORM="linux32" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
+#    - HOST=i686-pc-linux-gnu PLATFORM="linux32" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
 # Linux 64-bit + stone
     - HOST=x86_64-pc-linux-gnu PLATFORM="linux64" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
 # Linux stoned
-    - HOST=x86_64-pc-linux-gnu PLATFORM="linux-no-qt" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
+ #   - HOST=x86_64-pc-linux-gnu PLATFORM="linux-no-qt" PPA="ppa:bitcoin/bitcoin" PACKAGES="g++-multilib bc python3-zmq" DEP_OPTS="NO_QT=1" RUN_TESTS=false GOAL="install" BITCOIN_CONFIG="--enable-zmq --enable-glibc-back-compat --enable-reduce-exports LDFLAGS=-static-libstdc++" USE_SHELL="/bin/dash" PYZMQ=true
 # No wallet
 #    - HOST=x86_64-unknown-linux-gnu PLATFORM="unknown-linux-no-wallet" PPA="ppa:bitcoin/bitcoin" PACKAGES="python3" DEP_OPTS="NO_WALLET=1" RUN_TESTS=true GOAL="install" BITCOIN_CONFIG="--enable-glibc-back-compat --enable-reduce-exports"
 # Cross-Mac
-    - HOST=x86_64-apple-darwin11 PLATFORM="osx" PPA="ppa:bitcoin/bitcoin" PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" OSX_SDK=10.9 GOAL="deploy"
-
+#    - HOST=x86_64-apple-darwin11 PLATFORM="osx" PPA="ppa:bitcoin/bitcoin" PACKAGES="cmake imagemagick libcap-dev librsvg2-bin libz-dev libbz2-dev libtiff-tools python-dev" BITCOIN_CONFIG="--enable-gui --enable-reduce-exports" OSX_SDK=10.9 GOAL="deploy"
 before_install:
-    - git clone https://github.com/stone/stone_hash.git
-    - travis_retry sudo apt-get install python-dev
-    - travis_retry sudo add-apt-repository ppa:ubuntu-wine/ppa -y
-    - export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" | sed "s|::|:|g")
+- git clone https://github.com/CryptoDragonLady/Stonecoin
+- travis_retry sudo apt-get install python-dev
+- travis_retry sudo add-apt-repository ppa:ubuntu-wine/ppa -y
+- openssl aes-256-cbc -K $encrypted_a20a463ac81c_key -iv $encrypted_a20a463ac81c_iv
+  -in deploy_rsa.enc -out deploy_rsa -d
+- export PATH=$(echo $PATH | tr ':' "\n" | sed '/\/opt\/python/d' | tr "\n" ":" |
+  sed "s|::|:|g")
 install:
-    - if [ "$PYZMQ" = "true" ]; then pip install pyzmq --user ; fi
-    - if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
-    - if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
-    - if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends --no-upgrade -qq $PACKAGES; fi
-    - cd stone_hash && python setup.py install --user && cd ..
+- if [ -n "$PPA" ]; then travis_retry sudo add-apt-repository "$PPA" -y; fi
+- if [ -n "$DPKG_ADD_ARCH" ]; then sudo dpkg --add-architecture "$DPKG_ADD_ARCH" ;
+  fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get update; fi
+- if [ -n "$PACKAGES" ]; then travis_retry sudo apt-get install --no-install-recommends
+  --no-upgrade -qq $PACKAGES; fi
+- export BDB_INCLUDE_PATH="/usr/include"
+- export BDB_LIB_PATH="/usr/lib"
 before_script:
-    - unset CC; unset CXX
-    - unset DISPLAY
-    - mkdir -p depends/SDKs depends/sdk-sources
-    - if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
-    - make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+- unset CC; unset CXX
+- if [ $CHECK_DOC -eq 1 ]; then contrib/devtools/check-doc.py; fi
+- mkdir -p depends/SDKs depends/sdk-sources
+- if [ -n "$OSX_SDK" -a ! -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  curl --location --fail $SDK_URL/MacOSX${OSX_SDK}.sdk.tar.gz -o depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz;
+  fi
+- if [ -n "$OSX_SDK" -a -f depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz ]; then
+  tar -C depends/SDKs -xf depends/sdk-sources/MacOSX${OSX_SDK}.sdk.tar.gz; fi
+- echo -e $MAKEJOBS $HOST $DEP_OPTS
+- echo -e $PYZMQ $OSX_SDK $PPA $PACKAGES $PATH $OUTDIR $USE_SHELL $GOAL
+- sudo make $MAKEJOBS -C depends HOST=$HOST $DEP_OPTS
+- chmod 600 deploy_rsa && mv deploy_rsa ~/.ssh/id_rsa
 script:
-    - if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
-    - OUTDIR=$BASE_OUTDIR/$TRAVIS_PULL_REQUEST/$TRAVIS_JOB_NUMBER-$HOST
-    - BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
-    - depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
-    - test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
-    - "./configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)"
-    - make distdir PACKAGE=stone VERSION=$HOST
-    - cd stone-$HOST
-    - "./configure --cache-file=../config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || ( cat config.log && false)"
-    - make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && make $GOAL V=1 ; false )
-    - export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
-    - if [ "$RUN_TESTS" = "true" -a "$WINE" != "true" ]; then make $MAKEJOBS check VERBOSE=1; fi
-    - if [ "$RUN_TESTS" = "true" -a "$WINE" = "true" ]; then wine  src/test/test_stone.exe; fi
-    #- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
+- export TRAVIS_COMMIT_LOG=`git log --format=fuller -1`
+- if [ -n "$USE_SHELL" ]; then export CONFIG_SHELL="$USE_SHELL"; fi
+- export BDB_INCLUDE_PATH="/usr/include"
+- export BDB_LIB_PATH="/usr/lib"
+- BITCOIN_CONFIG_ALL="--disable-dependency-tracking --prefix=$TRAVIS_BUILD_DIR/depends/$HOST --bindir=$OUTDIR/bin --libdir=$OUTDIR/lib"
+- depends/$HOST/native/bin/ccache --max-size=$CCACHE_SIZE
+- test -n "$USE_SHELL" && eval '"$USE_SHELL" -c "./autogen.sh"' || ./autogen.sh
+- mkdir build && cd build
+- "../configure --cache-file=config.cache $BITCOIN_CONFIG_ALL $BITCOIN_CONFIG || (
+  cat config.log && false)"
+- make -C .. distdir PACKAGE=stone VERSION=$HOST
+- cd stone-$HOST
+- make -C .. depend
+- ls
+- pwd
+- sudo make $MAKEJOBS $GOAL || ( echo "Build failure. Verbose build follows." && sudo
+  make $GOAL V=1 ; false )
+- export LD_LIBRARY_PATH=$TRAVIS_BUILD_DIR/depends/$HOST/lib
+- if [ "$RUN_TESTS" = "true" ]; then sudo make $MAKEJOBS check VERBOSE=1; fi
+- if [ "$RUN_TESTS" = "true" ]; then qa/pull-tester/rpc-tests.py --coverage; fi
 after_script:
-    - if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then (echo "Upload goes here. Something like: scp -r $BASE_OUTDIR server" || echo "upload failed"); fi
+- echo $TRAVIS_COMMIT_RANGE
+- echo $TRAVIS_COMMIT_LOG
+- ls -al $OUTDIR
+- pwd 
+- ls
 before_deploy:
-    - if [[ "$PLATFORM" = *"linux"* ]]; then cd $OUTDIR/bin && tar -cvzf $OUTDIR/bin/stone-$PLATFORM-$TRAVIS_TAG.tar.gz stone*; fi
-    - if [[ "$PLATFORM" = *"win"* ]]; then zip -j $OUTDIR/bin/stone-$PLATFORM-$TRAVIS_TAG.zip $OUTDIR/bin/stone*; fi
-    - if [[ "$PLATFORM" = *"osx"* ]]; then mkdir -p $OUTDIR/bin && cp Proton-Core.dmg $OUTDIR/bin/stone-$PLATFORM-$TRAVIS_TAG.dmg; fi
+- cd /home/travis/build/CryptoDragonLady/stone/; find . |grep tar.gz
+- find . |grep dmg
+- if [ -n "$OSX_SDK" ]; then cp ./$RNAME/stone-Core.dmg ./$RNAME.dmg; fi
+- if [ -n "$OSX_SDK" ]; then ./scripts/relpush.sh $RNAME.dmg; export FRNAME=$RNAME.dmg
+  ; fi
+- if [ -z "$OSX_SDK" ]; then ./scripts/relpush.sh $RNAME.tar.gz; export FRNAME=$RNAME.tar.gz
+  ; fi
+- ssh stone@88.198.86.0 "/var/www/files.worxcoin.io/htdocs/reldir-s.sh $GITCOM"
+- echo $FRNAME $GITCOM
+- ssh stone@88.198.86.0 "/var/www/files.worxcoin.io/htdocs/relmove-s.sh $FRNAME $GITCOM"
+after_success:
+- export RNAME=$HOST-$BVER
+- export OUTDIR=/home/travis/build/CryptoDragonLady/stone/$RNAME
+- git config --local user.name "CryptoDragonLady"
+- git config --local user.email "webmaster@stonecoin.io"
+- git tag "$RNAME-$(git log --format=%h -1)-$RBITS"
+- export RNAME=$RNAME-$(git log --format=%h -1)-$RBITS
+- export GITCOM=$(git log --format=%h -1)
+- mkdir /home/travis/build/CryptoDragonLady/stone/$RNAME
+- if [[ -n "/home/travis/build/CryptoDragonLady/stone/build/stone-i686-w64-mingw32/stone-$BVER-win32-setup.exe"
+  ]]; then cp /home/travis/build/CryptoDragonLady/stone/build/stone-i686-w64-mingw32/stone-$BVER-win32-setup.exe
+  /home/travis/build/CryptoDragonLady/stone/$RNAME ; fi
+- if [[ -n "/home/travis/build/CryptoDragonLady/stone/build/stone-x86_64-w64-mingw32/stone-$BVER-win64-setup.exe"
+  ]]; then cp /home/travis/build/CryptoDragonLady/stone/build/stone-x86_64-w64-mingw32/stone-$BVER-win64-setup.exe
+  /home/travis/build/CryptoDragonLady/stone/$RNAME ; fi
+- mkdir /home/travis/build/CryptoDragonLady/stone/$RNAME/lib
+- if [ -n "$OSX_SDK" ]; then cp /home/travis/build/CryptoDragonLady/stone/build/stone-x86_64-apple-darwin11/stone-Core.dmg
+  /home/travis/build/CryptoDragonLady/stone/$RNAME/; cd /home/travis/build/CryptoDragonLady/stone/$RNAME/;
+  fi
+- if [ -z "$OSX_SDK" ]; then cp /lib/libbitcoin* /home/travis/build/CryptoDragonLady/stone/$RNAME/lib/;
+  ls /lib; fi
+- if [ -z "$OSX_SDK" ]; then cp /bin/stone* /home/travis/build/CryptoDragonLady/stone/$RNAME/;
+  cd /home/travis/build/CryptoDragonLady/stone; fi
+- if [ -z "$OSX_SDK" ]; then tar -cf $RNAME.tar $RNAME && gzip -9 $RNAME.tar; fi
+- ls -al /home/travis/build/CryptoDragonLady/stone/$RNAME/.*
+- if [ -n "$OSX_SDK" ]; then "/home/travis/build/CryptoDragonLady/stone/scripts/relpush.sh
+  /home/travis/build/CryptoDragonLady/stone/$RNAME/stone-Core.dmg"; fi
+- if [ -n "$OSX_SDK" ]; then "cp /home/travis/build/CryptoDragonLady/stone/$RNAME/stone-Core.dmg
+  /home/travis/build/CryptoDragonLady/stone/$RNAME.dmg"; fi
+- if [ -z "$OSX_SDK" ]; then "/home/travis/build/CryptoDragonLady/stone/scripts/relpush.sh
+  /home/travis/build/CryptoDragonLady/stone/$RNAME.tar.gz"; fi
 deploy:
-    provider: releases
-    api_key:
-      secure: LlorZZRaFCo888opatoQIgZIhXDL905qVT/8T9V0cN285uYnoLp6rRdztOgZ/Bq71ii1wk67FzOeBNkKP05PfqMTB8wB96hwFOI4HkznqLbW8CnoQNR0T+sakwBlYACz2lw1QASSRrR6/AMWNlvDUdxfQkFg95eGAT8e/y34JAb8VHrMO3qdTJls+4kTxFtwiQxDVgJmm9V22+dz2Nd0CIdHkgurtPXeSoaDAuTvRbm9ZjCHDLWu+1t94bZ/2IQkx5No3jP8UcvDLlCMztsasU9ow9vgkShxM/UCb2S2gFCjfDjCV0rAm0pWpDhnVFvwKrXdV34E/nYZj3hHUTb7LwgYOl9PcMxrqqUZYpW1FU1LGaPoIOe7Nikjek/yg8XdXiPX4a1OzGDXrOBOzWwNdFKFdAuqbqSStIXZt5QBSVSILg8CRd3VWjDBtusmH+oz/lO/1HRW7tMw18UBMQlUIjThADUgoGBGYWvaMPWw3lyTzvbOyoj313WKpy/5WbArHZ/u2SGWdVTrgOktg+H8R91TNM/I4UYNr+shnHH2zIIJYaKHgzMCwuvwTcIerwS5dS+oBIFmJYkIfSqvWYAAxh2Si4qmgonq8o8yX1XIaGckeITgscehWNveIgWy7d7x876al1hj2s7ETi3RLn/SL/76Ix0dnYBmhbeR0u4zQQs=
-    file_glob: true
-    file: $OUTDIR/bin/stone-$PLATFORM-$TRAVIS_TAG*
-    skip_cleanup: true
-    on:
-      repo: stone/stone
-      tags: true 
+  provider: releases
+  api_key:
+    secure: SrIFjyo6R5dYkmGM5/MA4qnzmw++kO2Ri/kIZ7WFKkX4VJpUV7OH3lv3GaXP1wjwI0Ic4TBMwoy1CmZad0PJKXSOsPz2zSg5jE34Ty8TtWqP5D/j9QMMHEmdofNqewROvh3W+/lISVlGY3w7L06k9DCxZDpPRB/mWBlAeyTb2TFj0Sohf1dCykvenTAbDZ8frt5ZESVFSp7YQDYW4gs3+VknMucq0ukJemDIwGKFmH8muVLeO5uSh+EHNsunKxUN4nx1ZmAJfhFUh3r/bc+4nkdxGBYjEL8daAd2hWY419myzDOx7eC1xzOJjImjW+lWGT2YwB467R5olEo22Wk5onMUWu2sgGeSnhNkMpwRaV4uA18L2+iaV9WUfr5OYJpiiPrPwsaZVhg4DlAEvMdRKyD0lXkgSc4Bq8WBYwqIOonAugEMy3qRhy4derdohpV75Y78HJKkRCSKOIeGtoH3WSl0ZiBhwttHHkzMcwD0+s8JyqQgQC/5HGGHQJPdmxjQYn/iGAeJCiztXS44ICj7R15otOzz3x0DEaLksYLXH8zP6Ke+Xo+GRTPnCB9J9uCDJasLxk1icJzAAZ36mvhYhkReIX1Ss1q3TFUFOjFKoY2k1rMNIlQLlR0dbChoEvWaP9JzwfJT6zNQaTe8vXqofVxvT2BPG5vOKFmg0AicUFo=
+  file: "/home/travis/build/CryptoDragonLady/stone/build/stone-i686-w64-mingw32/stone*.dmg"
+  skip_cleanup: true
+  on: 
+repo: CryptoDragonLady/stone
